FEATURE_OPTIONS = {
    "work_type": [
        'Casual/Vacation',
        'Contract/Temp',
        'Full Time',
        'Part Time'
    ],
    "classification": [
        'Accounting',
        'Administration & Office Support',
        'Advertising, Arts & Media',
        'Banking & Financial Services',
        'CEO & General Management',
        'Call Centre & Customer Service',
        'Community Services & Development',
        'Construction',
        'Consulting & Strategy',
        'Design & Architecture',
        'Education & Training',
        'Engineering',
        'Farming, Animals & Conservation',
        'Government & Defence',
        'Healthcare & Medical',
        'Hospitality & Tourism',
        'Human Resources & Recruitment',
        'Information & Communication Technology',
        'Insurance & Superannuation',
        'Legal',
        'Manufacturing, Transport & Logistics',
        'Marketing & Communications',
        'Mining, Resources & Energy',
        'Real Estate & Property',
        'Retail & Consumer Products',
        'Sales',
        'Science & Technology',
        'Self Employment',
        'Sport & Recreation',
        'Trades & Services'
    ],
    "Location": [
        'ACT',
        'Adelaide',
        'Adelaide Hills & Barossa',
        'Albany & Great Southern',
        'Albury Area',
        'Alice Springs & Central Australia',
        'Americas',
        'Asia Pacific',
        'Auckland',
        'Bairnsdale & Gippsland',
        'Ballarat & Central Highlands',
        'Bay of Plenty',
        'Bendigo, Goldfields & Macedon Ranges',
        'Blue Mountains & Central West',
        'Brisbane',
        'Broome & Kimberley',
        'Bunbury & South West',
        'Bundaberg & Wide Bay Burnett',
        'Cairns & Far North',
        'Canterbury',
        'Central & South East TAS',
        'Coffs Harbour & North Coast',
        'Coober Pedy & Outback SA',
        'Darwin',
        'Devonport & North West',
        'Dubbo & Central NSW',
        'Europe & Russia',
        'Far West & North Central NSW',
        'Fleurieu Peninsula & Kangaroo Island',
        'Geraldton, Gascoyne & Midwest',
        'Gisborne',
        'Gladstone & Central QLD',
        'Gold Coast',
        'Gosford & Central Coast',
        'Hawkes Bay',
        'Hervey Bay & Fraser Coast',
        'Hobart',
        'Horsham & Grampians',
        'Ireland',
        'Kalgoorlie, Goldfields & Esperance',
        'Katherine & Northern Australia',
        'Launceston & North East',
        'Lismore & Far North Coast',
        'London',
        'Mackay & Coalfields',
        'Manawatu',
        'Mandurah & Peel',
        'Marlborough',
        'Melbourne',
        'Middle East & Africa',
        'Mildura & Murray',
        'Mornington Peninsula & Bass Coast',
        'Mt Gambier & Limestone Coast',
        'Newcastle, Maitland & Hunter',
        'Northam & Wheatbelt',
        'Northern QLD',
        'Northland',
        'Otago',
        'Perth',
        'Port Hedland, Karratha & Pilbara',
        'Port Macquarie & Mid North Coast',
        'Rest of the UK',
        'Richmond & Hawkesbury',
        'Riverland & Murray Mallee',
        'Rockhampton & Capricorn Coast',
        'Shepparton & Goulburn Valley',
        'Somerset & Lockyer',
        'South West Coast VIC',
        'Southern Highlands & Tablelands',
        'Southland',
        'Sunshine Coast',
        'Sydney',
        'Tamworth & North West NSW',
        'Taranaki',
        'Tasman',
        'Toowoomba & Darling Downs',
        'Tumut, Snowy & Monaro',
        'Wagga Wagga & Riverina',
        'Waikato',
        'Wellington',
        'West Coast',
        'West Gippsland & Latrobe Valley',
        'Western QLD',
        'Whyalla & Eyre Peninsula',
        'Wollongong, Illawarra & South Coast',
        'Yarra Valley & High Country',
        'Yorke Peninsula & Clare Valley'
    ]

}
